"""message

Revision ID: 0996de2512a6
Revises: 712f667b4e96
Create Date: 2023-10-04 07:00:10.243043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0996de2512a6'
down_revision = '712f667b4e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forms_department_id_employees', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_forms_department_id_employees', 'employees', ['department_id'], ['department_id'])

    # ### end Alembic commands ###
