"""message

Revision ID: 1beec13ba86f
Revises: c6d07c921fd7
Create Date: 2023-10-04 06:54:40.080779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1beec13ba86f'
down_revision = 'c6d07c921fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forms_department_id_departments', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_forms_department_id_employees'), 'employees', ['department_id'], ['department_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_forms_department_id_employees'), type_='foreignkey')
        batch_op.create_foreign_key('fk_forms_department_id_departments', 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###
