"""message

Revision ID: 3496403fa30c
Revises: 0996de2512a6
Create Date: 2023-10-04 07:01:02.291386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3496403fa30c'
down_revision = '0996de2512a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_forms_employee_id_employees'), 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_forms_employee_id_employees'), type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
