"""message

Revision ID: 712f667b4e96
Revises: 1beec13ba86f
Create Date: 2023-10-04 06:57:35.534163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712f667b4e96'
down_revision = '1beec13ba86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forms_employee_id_employees', type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_forms_employee_id_employees', 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###
