"""message

Revision ID: 8022c4ed8f90
Revises: d6283fe4b002
Create Date: 2023-10-04 07:37:55.232839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8022c4ed8f90'
down_revision = 'd6283fe4b002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_forms_site_id_sites'), 'sites', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_forms_site_id_sites'), type_='foreignkey')
        batch_op.drop_column('site_id')

    # ### end Alembic commands ###
