"""message

Revision ID: adbe031c1bd9
Revises: 8022c4ed8f90
Create Date: 2023-10-10 14:05:21.230792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbe031c1bd9'
down_revision = '8022c4ed8f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer1', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('answer2', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('answer3', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('answer4', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('answer5', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=False))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('comments')
        batch_op.drop_column('answer5')
        batch_op.drop_column('answer4')
        batch_op.drop_column('answer3')
        batch_op.drop_column('answer2')
        batch_op.drop_column('answer1')

    # ### end Alembic commands ###
