"""message

Revision ID: d06a73b207b1
Revises: ca493d5dd010
Create Date: 2023-10-10 20:57:02.856600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06a73b207b1'
down_revision = 'ca493d5dd010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('question1', sa.String(), nullable=False),
    sa.Column('question2', sa.String(), nullable=False),
    sa.Column('question3', sa.String(), nullable=False),
    sa.Column('question4', sa.String(), nullable=False),
    sa.Column('question5', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
