"""message

Revision ID: d6283fe4b002
Revises: f7a1aad8f5b3
Create Date: 2023-10-04 07:36:51.721662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6283fe4b002'
down_revision = 'f7a1aad8f5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_forms_department_id_departments'), 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_forms_department_id_departments'), type_='foreignkey')

    # ### end Alembic commands ###
