"""message

Revision ID: f7a1aad8f5b3
Revises: 3496403fa30c
Create Date: 2023-10-04 07:29:23.201469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a1aad8f5b3'
down_revision = '3496403fa30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('department_forms')
    op.drop_table('site_forms')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_employees_site_id_sites'), 'sites', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employees_site_id_sites'), type_='foreignkey')
        batch_op.drop_column('site_id')

    op.create_table('site_forms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('form_id', sa.INTEGER(), nullable=True),
    sa.Column('admin_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['employees.id'], name='fk_site_forms_admin_id_employees'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name='fk_site_forms_form_id_forms'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_forms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('form_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_department_forms_department_id_departments'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name='fk_department_forms_form_id_forms'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name='fk_department_forms_manager_id_employees'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sites')
    # ### end Alembic commands ###
